/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package util;

/**
 *
 * @author ACER
 */
public class CursosComvalidado extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConvalidacionCurricular
     */
    public CursosComvalidado() {
        initComponents();
        setSize(550, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CURSOS CONVALIDADOS");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Alumno "));
        jPanel1.setAutoscrolls(true);
        jPanel1.setName("Datos del Alumno "); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setText("Alumno:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 54, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 30, 370, 26);

        jLabel2.setText("Codigo :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 56, 50, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(80, 60, 280, 26);

        jLabel3.setText("Especialidad:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 80, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(100, 90, 350, 30);

        jLabel4.setText("Plan de Estudio  Original y destino :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 130, 190, 16);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(210, 126, 75, 30);

        jLabel5.setText(">>");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 130, 20, 20);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(340, 126, 80, 30);

        jLabel6.setText("Fecha de  emisión :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 166, 120, 20);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(140, 160, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 480, 210);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Convalidados"));
        jPanel2.setLayout(null);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 204))); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cursos no convalidados ", "cursos convalidados ", "creditos del curso ", "creditos equivalentes "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 450, 300);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 240, 480, 350);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen de creditos "));
        jPanel3.setLayout(null);

        jLabel7.setText("Creditos \"perdidos\"o no convalidados:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(11, 24, 210, 16);

        jLabel8.setText("Creditos totales requeridos del nuevo plan:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 50, 230, 16);

        jLabel9.setText("Creditos totales convalidados:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 80, 230, 16);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(230, 20, 170, 26);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(250, 50, 150, 26);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(180, 80, 150, 26);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(580, 60, 440, 130);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setText("GUARDAR REPORTE");
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 250, 160, 27);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setText("EXPORTAR A EXCEL ");
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 290, 160, 27);

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setText("LIMPIAR / NUEVA COMVALIDACION ");
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 330, 240, 27);

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setText("SALIR ");
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 370, 190, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
