/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package util;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Asignatura;
import modelo.LectorExcel;
import java.io.File;
import java.util.List;

import javax.swing.JFileChooser;

public class DatosAlum extends javax.swing.JInternalFrame {

    /**
     * Creates new form DatosAlum
     */
    public DatosAlum() {
        initComponents();
        setSize(550, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jBUSCAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jBCANCELAR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("DATOS DEL ALUMNO ");
        setAutoscrolls(true);
        setVisible(true);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 30, 190, 26);

        jBUSCAR.setBackground(new java.awt.Color(51, 153, 255));
        jBUSCAR.setText("BUSCAR");
        jBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUSCARActionPerformed(evt);
            }
        });
        getContentPane().add(jBUSCAR);
        jBUSCAR.setBounds(248, 30, 90, 27);

        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 70, 16);

        jLabel2.setText("Alumno");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 50, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(90, 70, 390, 26);

        jLabel3.setText("Codigo ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 50, 16);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(90, 110, 230, 26);

        jLabel4.setText("Codigo de Curricula");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 120, 16);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 150, 220, 26);

        jLabel5.setText("Especialidad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 110, 16);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(110, 200, 320, 26);

        jBCANCELAR.setBackground(new java.awt.Color(255, 102, 102));
        jBCANCELAR.setText("CANCELAR");
        getContentPane().add(jBCANCELAR);
        jBCANCELAR.setBounds(350, 30, 100, 27);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("RECORD"));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Ciclo ", "Código", "Curso", "Nota", "Créditos", "Veces"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 470, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 270, 490, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUSCARActionPerformed
        
     String codigoIngresado = jTextField1.getText().trim();

    if (codigoIngresado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un código de alumno.");
        return;
    }

    try {
        // Ruta fija del archivo Excel
        File archivo = new File("data/dataalumno.xlsx");

        // Leer los datos desde el archivo
        LectorExcel lector = new LectorExcel();
        List<Object[]> datos = lector.leerAlumnoDesdeExcel(archivo);

        // Filtrar los datos por código ingresado
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiar la tabla

        boolean encontrado = false;
        for (Object[] fila : datos) {
            String codigoAlumno = fila[2].toString(); // columna 2 es el código
            if (codigoAlumno.equalsIgnoreCase(codigoIngresado)) {
                modelo.addRow(fila);
                encontrado = true;

                // Rellenar campos de datos del alumno (simulado)
                jTextField2.setText("Nombre del alumno"); // Aquí puedes extraerlo si lo tienes en otra hoja o parte
                jTextField3.setText(fila[2].toString()); // Código
                jTextField4.setText("2022-1"); // Simulado: puedes leerlo si está en el Excel
                jTextField5.setText("Ingeniería de Sistemas"); // Simulado
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontró el alumno con ese código.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar el archivo de alumnos.");
    }
    }//GEN-LAST:event_jBUSCARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCANCELAR;
    private javax.swing.JButton jBUSCAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
